# setupmvillage-bell-recipec.com
services:
  mc:
    image: itzg/minecraft-server:latest
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
      - "8123:8123"
    environment:
      EULA: "TRUE"
      TYPE: "MODRINTH"
      DIFFICULTY: "2"
      VERSION: "1.21.5"
      MODRINTH_MODPACK: "https://modrinth.com/modpack/adrenaline"
      MODRINTH_ALLOWED_VERSION_TYPE: "alpha"
      MODRINTH_DEFAULT_VERSION_TYPE: "alpha"
      MODRINTH_LOADER: "fabric"
#      MODS: |-
#        [LINK TO .JAR FILE HERE]
      MEMORY: "8G"
      MAX_PLAYERS: "10"
      MOTD: "A Special Message!"
      ICON: "[LINK TO IMAGE HERE]"
      TZ: "America/New_York"
      ENABLE_COMMAND_BLOCK: "true"
      ENABLE_WHITELIST: "true"
      WHITELIST: |-
        player1
        player2
        player3
        player4
        player5
      SEED: "69420114477378524"
      SIMULATION_DISTANCE: "8"
      VIEW_DISTANCE: "10"
      SPAWN_PROTECTION: "0"
      SYNC_CHUNK_WRITES: "false"
      OPS: |-
        player1
      MODRINTH_PROJECTS: |-
        spark
        chunky
        architectury-api
        balm
        collective
        fabric-language-kotlin
        jamlib
        adjusted-phantom-spawns
        alternate-current
        anvil-restoration
        better-spawner-control
        bigger-sponge-absorption-radius
        compact-help-command
        debugify
        double-doors
        end-portal-recipe
        fastback
        fish-on-the-line
        fixed-anvil-repair-cost
        followers-teleport-too
        grind-enchantments
        indypets
        inventory-management
        inventory-totem
        journeymap
        merge-enchantments
        name-tag-tweaks
        netherportalfix
        no-chat-reports
        our-villager-discounts
        rei
        rightclickharvest
        too-cheap
        too-fast
        tree-harvester
        vanilla-refresh
        village-bell-recipe
        villager-converting
        warden-with-loot
        datapack:blasting-plus
        datapack:dungeons+
        datapack:dungeons-and-taverns-pillager-outpost-overhaul
        datapack:dungeons-and-taverns-swamp-hut-overhaul
        datapack:dungeons-and-taverns-jungle-temple-overhaul
        datapack:dungeons-and-taverns-ocean-monument-overhaul
        datapack:dungeons-and-taverns-desert-temple-overhaul
        datapack:enchanted-golden-apple-addition
        datapack:geophilic
        datapack:leash-villager
        datapack:mastercutter
        datapack:refined-advancements
        datapack:veinminer
        datapack:veinminer-enchantment
        datapack:waystones-data-pack
      MODRINTH_DOWNLOAD_DEPENDENCIES: "required"
      VANILLATWEAKS_SHARECODE: "your-share-code-here"
    volumes:
      - "./data:/data"
    restart: always
