services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    environment:
      - N8N_HOST=your-n8n-subdomain.yourdomain.duckdns.org
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://your-n8n-subdomain.yourdomain.duckdns.org/
      - GENERIC_TIMEZONE=America/New_York
      - N8N_PROXY_HOPS=1
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - DB_SQLITE_POOL_SIZE=5
      - N8N_RUNNERS_ENABLED=true
      - N8N_BLOCK_ENV_ACCESS_IN_NODE=true
      - N8N_GIT_NODE_DISABLE_BARE_REPOS=true
    volumes:
      - n8n_data:/home/node/.n8n
      - ./local-files:/files
    networks:
      - default

volumes:
  n8n_data:

networks:
  default:
    external: true
    name: docker_network
